### ISSUE TITLE
Not working after uploading the jar file to my bungee server

### ISSUE THREAD

**Issue by KahpotVanilla** [Lydark-Studio/LyLunarStar#1]
Hey, I've uploaded the jar to my bungecord server and the star doesn't show up, I'm on version 1.8.9 lunar
here's my plugins:
![image](https://user-images.githubusercontent.com/85695775/159777672-d41c4920-f9b6-4ace-a0b3-62d6b5d517cd.png)

**Comment by BarraR3port** [comment]
I think it might be an issue with another plugin, maybe the ServerListPlus.

**Comment by KahpotVanilla** [comment]
Then add support for serverlistplus, how do I supposed to change MOTD?
